import type { NextPage } from 'next'
import Head from 'next/head'
import First from '../components/First'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Blogr </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bg-pattern-intro.svg" sizes="32X32" />
      </Head>

      <First />
    </div>
  )
}

export default Home
